### ISSUE TITLE
delete_group function doesn't get the keys from the given group

### ISSUE THREAD

**Issue by drawpause** [devgeniem/wp-redis-group-cache#2]
/classes/cache.php:81

```
 $keys = self::$redis_instance->hkeys( $group ); // returns an empty array
```

The cache key along it's group was set successfully earlier, or at least the cache was set and readable. I Don't know if the group key was saved to Redis successfully.

**Comment by Pikkulahti** [comment]
I second this: 
When adding 
```php
\Geniem\GroupCache::delete_group('SomeGroup');
```
for example to the `save_post` hook causes a fatal error when saving the post. Probably if cache is not yet set.
```
Fatal error: Uncaught Error: Call to a member function hkeys() on null in /var/www/project/web/app/plugins/wp-redis-group-cache/classes/cache.php:81
```
Shouldn't the function itself contain some logic to prevent an error like this?

**Comment by villesiltala** [comment]
@Pikkulahti see plugin.php on lines 17-22.
```
// Use this plugin only if Redis is enabled in WP Object Cache.
if ( method_exists( $wp_object_cache, 'redis_status' ) && true === $wp_object_cache->redis_status() ) {
    GroupCache::set_redis_instance( $wp_object_cache->redis_instance() );
} else {
    return;
}
```
If there is no Redis instance found, the plugin should stop working altogether. I will test this process again.

**Comment by villesiltala** [comment]
Closing this issue as stale.
