### ISSUE TITLE
Add some blacklisted groups

### ISSUE THREAD

**Issue by villesiltala** [devgeniem/wp-redis-group-cache#6]
These groups should not be handled by the plugin:

```
post_meta
post_tag_relationships
post_translations_relationships
language_relationships
term_language_relationships
term_translations_relationships
timeinfo
```

**Comment by godbone** [comment]
These will be added in https://github.com/devgeniem/wp-redis-group-cache/pull/7

**Comment by godbone** [comment]
https://github.com/devgeniem/wp-redis-group-cache/pull/7 has now been merged to master
